// <auto-generated />
using System;
using CsJudgeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsJudgeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922153523_AddContestQuestionRelationship")]
    partial class AddContestQuestionRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CsJudgeApi.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("CsJudgeApi.Models.Configuration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("CsJudgeApi.Models.Contest", b =>
                {
                    b.Property<int>("ContestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemesterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContestId");

                    b.HasIndex("SemesterId", "Group")
                        .HasDatabaseName("IX_Contest_SemesterGroup");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("CsJudgeApi.Models.ContestLanguage", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.HasKey("ContestId", "Language");

                    b.ToTable("ContestLanguage");
                });

            modelBuilder.Entity("CsJudgeApi.Models.ContestQuestion", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContestId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ContestId", "Order")
                        .HasDatabaseName("IX_ContestQuestion_ContestOrder");

                    b.ToTable("ContestQuestions");
                });

            modelBuilder.Entity("CsJudgeApi.Models.ContestStudent", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateParticipation")
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContestId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ContestStudents");
                });

            modelBuilder.Entity("CsJudgeApi.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPathValidatorSourceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CsJudgeApi.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SemesterCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SemesterId");

                    b.ToTable("Semesters");

                    b.HasData(
                        new
                        {
                            SemesterId = 1,
                            EndDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "2-2025",
                            SemesterCode = 20252,
                            StartDate = new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SemesterId = 2,
                            EndDate = new DateTime(2026, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "2-2026",
                            SemesterCode = 20262,
                            StartDate = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CsJudgeApi.Models.Student", b =>
                {
                    b.Property<long>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CsJudgeApi.Models.StudentSemester", b =>
                {
                    b.Property<long>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemesterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParallelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId", "SemesterId");

                    b.HasIndex("SemesterId", "Group")
                        .HasDatabaseName("IX_StudentSemester_SemesterGroup");

                    b.ToTable("StudentSemesters");
                });

            modelBuilder.Entity("CsJudgeApi.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildLog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemKb")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputActual")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputExpected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunLog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("SubmissionId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("CsJudgeApi.Models.ActivityLog", b =>
                {
                    b.HasOne("CsJudgeApi.Models.Contest", "Contest")
                        .WithMany()
                        .HasForeignKey("ContestId");

                    b.HasOne("CsJudgeApi.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId");

                    b.HasOne("CsJudgeApi.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Contest");

                    b.Navigation("Question");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CsJudgeApi.Models.Contest", b =>
                {
                    b.HasOne("CsJudgeApi.Models.Semester", "Semester")
                        .WithMany("Contests")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("CsJudgeApi.Models.ContestLanguage", b =>
                {
                    b.HasOne("CsJudgeApi.Models.Contest", "Contest")
                        .WithMany("Languages")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("CsJudgeApi.Models.ContestQuestion", b =>
                {
                    b.HasOne("CsJudgeApi.Models.Contest", "Contest")
                        .WithMany("Questions")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CsJudgeApi.Models.Question", "Question")
                        .WithMany("Contests")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CsJudgeApi.Models.ContestStudent", b =>
                {
                    b.HasOne("CsJudgeApi.Models.Contest", "Contest")
                        .WithMany("Students")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CsJudgeApi.Models.Student", "Student")
                        .WithMany("Contests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CsJudgeApi.Models.StudentSemester", b =>
                {
                    b.HasOne("CsJudgeApi.Models.Semester", "Semester")
                        .WithMany("Students")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CsJudgeApi.Models.Student", "Student")
                        .WithMany("Semesters")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CsJudgeApi.Models.Contest", b =>
                {
                    b.Navigation("Languages");

                    b.Navigation("Questions");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CsJudgeApi.Models.Question", b =>
                {
                    b.Navigation("Contests");
                });

            modelBuilder.Entity("CsJudgeApi.Models.Semester", b =>
                {
                    b.Navigation("Contests");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CsJudgeApi.Models.Student", b =>
                {
                    b.Navigation("Contests");

                    b.Navigation("Semesters");
                });
#pragma warning restore 612, 618
        }
    }
}
